# Netlify configuration for frontend-only deployment
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to a proper backend service
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-service.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200