[phases.setup]
nixPkgs = ['nodejs_18', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'npm ci --omit=dev',
  'cd brightbridgeDir && python3 -m pip install --user -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
PYTHONPATH = './brightbridgeDir'
PYTHON_VERSION = '3.11'